name: Build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Get Short Commit Hash
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set Version in Gradle Properties
        run: |
          sed -i "s/^mod_version=.*/mod_version=${{ steps.vars.outputs.sha_short }}/g" gradle.properties

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: maidindustry-build-${{ steps.vars.outputs.sha_short }}
          path: build/libs/*.jar
